// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopGYM.Data.EF;

#nullable disable

namespace ShopGYM.Data.Migrations
{
    [DbContext(typeof(ShopGYMDbContext))]
    [Migration("20250704061531_database")]
    partial class database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            RoleId = new Guid("5bc70ed5-b04d-4b8f-9fc0-588f0e6c1962")
                        },
                        new
                        {
                            UserId = new Guid("bb100ea3-aa44-42da-f858-08ddb2449214"),
                            RoleId = new Guid("b4a61976-a013-4c49-af27-3eff86cb4a25")
                        },
                        new
                        {
                            UserId = new Guid("90b411be-a570-4839-8f59-492edcc9520d"),
                            RoleId = new Guid("8e15262e-8583-4c49-86be-cef2bf4345d1")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4a61976-a013-4c49-af27-3eff86cb4a25"),
                            MoTa = "Nhân viên",
                            Name = "NhanVien",
                            NormalizedName = "NhanVien"
                        },
                        new
                        {
                            Id = new Guid("5bc70ed5-b04d-4b8f-9fc0-588f0e6c1962"),
                            MoTa = "Khách hàng",
                            Name = "KhachHang",
                            NormalizedName = "KhachHang"
                        },
                        new
                        {
                            Id = new Guid("8e15262e-8583-4c49-86be-cef2bf4345d1"),
                            MoTa = "Quan Tri",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f518d7a4-a59e-40f7-8076-a42d549cea2b",
                            Dob = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iuytutgyu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Tung",
                            LastName = "test1",
                            LockoutEnabled = true,
                            NormalizedEmail = "IUYTUTGYU@GMAIL.COM",
                            NormalizedUserName = "TUNG1",
                            PasswordHash = "AQAAAAIAAYagAAAAECstnv1pwi32bsYGqUrk8Ty+qp9tERfUmi7TkUPoBbcDAMlqaNz8m+PMb6Kd6cs+DA==",
                            PhoneNumber = "877845832",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "PQG4BV4ZOAADMF42KJCZYXOWJY56WETU",
                            TwoFactorEnabled = false,
                            UserName = "Tung1"
                        },
                        new
                        {
                            Id = new Guid("bb100ea3-aa44-42da-f858-08ddb2449214"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bc86b57-7eed-4cfe-8fde-087c544822b6",
                            Dob = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iuytutgyusaduw@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nguyen",
                            LastName = "Nam",
                            LockoutEnabled = true,
                            NormalizedEmail = "IUYTUTGYUSADUW@GMAIL.COM",
                            NormalizedUserName = "NAM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKsZaSL4UT2Ktcmm8MP58qEHdMOkoK/fhkWY3yXAm93y3reJc1xjGEOP+W+un8P5TA==",
                            PhoneNumber = "03858445213",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "I4A55LKLPNEJTJZ4VHFC5AHXYYQU55WM",
                            TwoFactorEnabled = false,
                            UserName = "Nam"
                        },
                        new
                        {
                            Id = new Guid("90b411be-a570-4839-8f59-492edcc9520d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "578401e0-da12-431f-89c0-bc8e44c0d119",
                            Dob = new DateTime(2003, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nguyenthanhutung0168I@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nguyen",
                            LastName = "Thanh Tung",
                            LockoutEnabled = false,
                            NormalizedEmail = "NGUYENTHANHUTUNG0168I@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEM46oTWgZoplJc03cruZtbZl0U+oFphoPy/WIUKRg7ddeIhiiLck/8cFrJw6UnM+MQ==",
                            PhoneNumber = "0385844597",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDonHang", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaDonHang = 48,
                            MaSanPham = 2,
                            Gia = 350000.00m,
                            SoLuong = 2
                        },
                        new
                        {
                            MaDonHang = 48,
                            MaSanPham = 3,
                            Gia = 150000.00m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDonHang = 49,
                            MaSanPham = 1,
                            Gia = 150000.00m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDonHang = 50,
                            MaSanPham = 14,
                            Gia = 200000.00m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDonHang = 51,
                            MaSanPham = 2,
                            Gia = 175000.00m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDonHang = 52,
                            MaSanPham = 2,
                            Gia = 175000.00m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDonHang = 52,
                            MaSanPham = 8,
                            Gia = 1200000.00m,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DanhGia", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhGia = 2,
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            MaSanPham = 2,
                            NgayDanhGia = new DateTime(2025, 5, 28, 21, 49, 29, 771, DateTimeKind.Utc).AddTicks(5274),
                            NoiDung = "ngon bổ đấy"
                        },
                        new
                        {
                            MaDanhGia = 4,
                            MaNguoiDung = new Guid("90b411be-a570-4839-8f59-492edcc9520d"),
                            MaSanPham = 2,
                            NgayDanhGia = new DateTime(2025, 5, 29, 15, 1, 46, 590, DateTimeKind.Utc).AddTicks(1833),
                            NoiDung = "hehehehe"
                        },
                        new
                        {
                            MaDanhGia = 5,
                            MaNguoiDung = new Guid("90b411be-a570-4839-8f59-492edcc9520d"),
                            MaSanPham = 2,
                            NgayDanhGia = new DateTime(2025, 5, 29, 15, 2, 0, 409, DateTimeKind.Utc).AddTicks(6741),
                            NoiDung = "hihihih"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            MoTa = "Quần các loại",
                            TenDanhMuc = "Quan"
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MoTa = "Áo thời trang",
                            TenDanhMuc = "Ao"
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            MoTa = "Giày thể thao và thời trang",
                            TenDanhMuc = "Giay"
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            MoTa = "Phụ kiện thời trang",
                            TenDanhMuc = "PhuKien"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaDonHang = 47,
                            DiaChiGiaoHang = "ểw",
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            NgayDatHang = new DateTime(2025, 5, 28, 20, 12, 46, 579, DateTimeKind.Utc).AddTicks(7613),
                            PhuongThucThanhToan = "Momo",
                            SDT = "0385844589",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đang giao"
                        },
                        new
                        {
                            MaDonHang = 48,
                            DiaChiGiaoHang = "ninh bình",
                            MaNguoiDung = new Guid("90b411be-a570-4839-8f59-492edcc9520d"),
                            NgayDatHang = new DateTime(2025, 6, 11, 10, 1, 53, 978, DateTimeKind.Utc).AddTicks(1287),
                            PhuongThucThanhToan = "Momo",
                            SDT = "0385844556",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đã giao"
                        },
                        new
                        {
                            MaDonHang = 49,
                            DiaChiGiaoHang = "ninh bình",
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            NgayDatHang = new DateTime(2025, 6, 12, 15, 45, 54, 17, DateTimeKind.Utc).AddTicks(9282),
                            PhuongThucThanhToan = "COD",
                            SDT = "0385844556",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đã giao"
                        },
                        new
                        {
                            MaDonHang = 50,
                            DiaChiGiaoHang = "ninh bình",
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            NgayDatHang = new DateTime(2025, 6, 12, 16, 9, 27, 631, DateTimeKind.Utc).AddTicks(5490),
                            PhuongThucThanhToan = "Momo",
                            SDT = "0385844556",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đang giao"
                        },
                        new
                        {
                            MaDonHang = 51,
                            DiaChiGiaoHang = "ểw",
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            NgayDatHang = new DateTime(2025, 6, 22, 15, 30, 13, 795, DateTimeKind.Utc).AddTicks(4134),
                            PhuongThucThanhToan = "COD",
                            SDT = "0385844389",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đang xử lý"
                        },
                        new
                        {
                            MaDonHang = 52,
                            DiaChiGiaoHang = "ninh bình",
                            MaNguoiDung = new Guid("47cafa38-48eb-4eff-0ac5-08dd955ceca4"),
                            NgayDatHang = new DateTime(2025, 7, 3, 16, 46, 50, 769, DateTimeKind.Utc).AddTicks(2810),
                            PhuongThucThanhToan = "COD",
                            SDT = "0385844592",
                            TenNguoiNhan = "tung",
                            TrangThai = "Đang xử lý"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSanPham");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("0");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaDanhGia");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HinhAnh", (string)null);

                    b.HasData(
                        new
                        {
                            MaHinhAnh = 1,
                            DuongDan = "/user-content/9d87f6cd-d4cb-4fe4-b3ad-3a835ec5963b.png",
                            IsDefault = true,
                            MaSanPham = 1,
                            Mota = "Hình quần jeans nam đẹp",
                            NgayTao = new DateTime(2025, 5, 14, 12, 53, 34, 82, DateTimeKind.Utc).AddTicks(1737)
                        },
                        new
                        {
                            MaHinhAnh = 2,
                            DuongDan = "/user-content/7b3698fa-690b-4b2d-b403-dbad0bd39ba1.png",
                            IsDefault = true,
                            MaSanPham = 2,
                            Mota = "Hình quần kaki nữ",
                            NgayTao = new DateTime(2025, 3, 26, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MaHinhAnh = 3,
                            DuongDan = "/user-content/5a960552-f331-450b-85bf-3922c6167f3e.png",
                            IsDefault = true,
                            MaSanPham = 3,
                            Mota = "Hình áo thun nam",
                            NgayTao = new DateTime(2025, 3, 26, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MaHinhAnh = 4,
                            DuongDan = "/user-content/44ca264f-7b2c-47a5-aca9-eafdc79684f8.png",
                            IsDefault = true,
                            MaSanPham = 4,
                            Mota = "Hình áo sơ mi nữ",
                            NgayTao = new DateTime(2025, 3, 26, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MaHinhAnh = 5,
                            DuongDan = "/user-content/94f71cd2-508a-4ef2-b000-8355bbd7a45e.png",
                            IsDefault = true,
                            MaSanPham = 5,
                            Mota = "Hình giày sneaker nam",
                            NgayTao = new DateTime(2025, 3, 26, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MaHinhAnh = 6,
                            DuongDan = "/user-content/bd8574b2-3ddb-4f5a-a90f-5a1033b8b965.webp",
                            IsDefault = false,
                            MaSanPham = 6,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 11, 8, 15, 13, 727, DateTimeKind.Utc).AddTicks(6523)
                        },
                        new
                        {
                            MaHinhAnh = 7,
                            DuongDan = "/user-content/d3b2f6c7-ff0f-4e88-9cf4-ecd5fd2b0c51.png",
                            IsDefault = true,
                            MaSanPham = 7,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 12, 18, 10, 30, 817, DateTimeKind.Utc).AddTicks(913)
                        },
                        new
                        {
                            MaHinhAnh = 12,
                            DuongDan = "/user-content/f3012e83-c8ed-4824-8cd4-f9a339daf8f2.webp",
                            IsDefault = true,
                            MaSanPham = 10,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 13, 14, 51, 32, 15, DateTimeKind.Utc).AddTicks(8324)
                        },
                        new
                        {
                            MaHinhAnh = 18,
                            DuongDan = "/user-content/35cc0df5-31ec-4738-b24d-7a2daf7627cb.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 23, 14, 25, 41, 921, DateTimeKind.Utc).AddTicks(388)
                        },
                        new
                        {
                            MaHinhAnh = 19,
                            DuongDan = "/user-content/36ceb809-f557-4bdd-bb39-1ae13e9f1e51.png",
                            IsDefault = false,
                            MaSanPham = 14,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 25, 13, 53, 33, 552, DateTimeKind.Utc).AddTicks(8252)
                        },
                        new
                        {
                            MaHinhAnh = 20,
                            DuongDan = "/user-content/e87db1f5-d929-4415-9428-a1a08dddec10.png",
                            IsDefault = false,
                            MaSanPham = 1,
                            Mota = "rẻ đẹp",
                            NgayTao = new DateTime(2025, 5, 25, 14, 49, 39, 140, DateTimeKind.Utc).AddTicks(5037)
                        },
                        new
                        {
                            MaHinhAnh = 21,
                            DuongDan = "/user-content/9e9ee8ab-390c-4ef0-b019-c2eac1ac955a.png",
                            IsDefault = false,
                            MaSanPham = 1,
                            Mota = "rẻ đẹp",
                            NgayTao = new DateTime(2025, 5, 25, 14, 49, 49, 149, DateTimeKind.Utc).AddTicks(5966)
                        },
                        new
                        {
                            MaHinhAnh = 22,
                            DuongDan = "/user-content/fb475d98-73f8-4f1b-8583-e6042b8d2622.png",
                            IsDefault = false,
                            MaSanPham = 1,
                            Mota = "test",
                            NgayTao = new DateTime(2025, 5, 25, 14, 49, 59, 834, DateTimeKind.Utc).AddTicks(412)
                        },
                        new
                        {
                            MaHinhAnh = 23,
                            DuongDan = "/user-content/12536c9c-8fdd-4bfb-bf1e-dc31ea195022.png",
                            IsDefault = false,
                            MaSanPham = 1,
                            Mota = "test",
                            NgayTao = new DateTime(2025, 5, 25, 14, 50, 10, 177, DateTimeKind.Utc).AddTicks(366)
                        },
                        new
                        {
                            MaHinhAnh = 24,
                            DuongDan = "/user-content/05eef3de-d0fb-493f-8019-ad5b6bc3bb5e.png",
                            IsDefault = false,
                            MaSanPham = 2,
                            Mota = "test",
                            NgayTao = new DateTime(2025, 5, 25, 14, 52, 43, 848, DateTimeKind.Utc).AddTicks(1474)
                        },
                        new
                        {
                            MaHinhAnh = 25,
                            DuongDan = "/user-content/5aeae558-cd6a-4665-a87a-69f84c73b225.png",
                            IsDefault = false,
                            MaSanPham = 2,
                            Mota = "rẻ đẹp",
                            NgayTao = new DateTime(2025, 5, 25, 14, 52, 55, 629, DateTimeKind.Utc).AddTicks(7785)
                        },
                        new
                        {
                            MaHinhAnh = 26,
                            DuongDan = "/user-content/cb8cfdd2-f5c9-41fd-b497-c2ac18bc747d.png",
                            IsDefault = false,
                            MaSanPham = 2,
                            Mota = "test",
                            NgayTao = new DateTime(2025, 5, 25, 14, 53, 5, 139, DateTimeKind.Utc).AddTicks(8127)
                        },
                        new
                        {
                            MaHinhAnh = 27,
                            DuongDan = "/user-content/7df6e485-fddc-48fc-b383-3776cb04e487.jpg",
                            IsDefault = false,
                            MaSanPham = 2,
                            Mota = "rẻ đẹp",
                            NgayTao = new DateTime(2025, 5, 25, 14, 53, 13, 685, DateTimeKind.Utc).AddTicks(5409)
                        },
                        new
                        {
                            MaHinhAnh = 28,
                            DuongDan = "/user-content/1f524bf7-d054-476d-893e-de25db4cb9a1.png",
                            IsDefault = false,
                            MaSanPham = 3,
                            Mota = "rẻ đẹp",
                            NgayTao = new DateTime(2025, 5, 25, 14, 55, 3, 739, DateTimeKind.Utc).AddTicks(9717)
                        },
                        new
                        {
                            MaHinhAnh = 29,
                            DuongDan = "/user-content/70361097-bc35-4b0c-b125-ac11c8db49d2.png",
                            IsDefault = false,
                            MaSanPham = 3,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 55, 22, 498, DateTimeKind.Utc).AddTicks(6399)
                        },
                        new
                        {
                            MaHinhAnh = 30,
                            DuongDan = "/user-content/bcfd0e3b-772c-4788-89e7-9b0d1d1fb882.png",
                            IsDefault = false,
                            MaSanPham = 3,
                            Mota = "test",
                            NgayTao = new DateTime(2025, 5, 25, 14, 55, 41, 630, DateTimeKind.Utc).AddTicks(2513)
                        },
                        new
                        {
                            MaHinhAnh = 31,
                            DuongDan = "/user-content/20fd60d1-282d-4560-95de-48c9cdcde892.png",
                            IsDefault = false,
                            MaSanPham = 4,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 57, 15, 376, DateTimeKind.Utc).AddTicks(1171)
                        },
                        new
                        {
                            MaHinhAnh = 32,
                            DuongDan = "/user-content/0480112b-2729-43aa-b6cd-262e00bfdf12.png",
                            IsDefault = false,
                            MaSanPham = 4,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 57, 32, 742, DateTimeKind.Utc).AddTicks(1256)
                        },
                        new
                        {
                            MaHinhAnh = 33,
                            DuongDan = "/user-content/a1dd908b-517c-4e23-b802-863e6960dc14.jpg",
                            IsDefault = false,
                            MaSanPham = 4,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 57, 43, 193, DateTimeKind.Utc).AddTicks(3090)
                        },
                        new
                        {
                            MaHinhAnh = 34,
                            DuongDan = "/user-content/fdd9b59d-3a23-44e9-9e1c-15060e5ca5f4.jpg",
                            IsDefault = false,
                            MaSanPham = 4,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 57, 51, 181, DateTimeKind.Utc).AddTicks(7814)
                        },
                        new
                        {
                            MaHinhAnh = 35,
                            DuongDan = "/user-content/7114c9fb-0473-403f-a164-ff27fe9fd86b.png",
                            IsDefault = false,
                            MaSanPham = 5,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 14, 59, 49, 263, DateTimeKind.Utc).AddTicks(1807)
                        },
                        new
                        {
                            MaHinhAnh = 36,
                            DuongDan = "/user-content/8802f344-f99d-4a51-92e2-fd939b2930e4.png",
                            IsDefault = false,
                            MaSanPham = 5,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 15, 0, 14, 239, DateTimeKind.Utc).AddTicks(4353)
                        },
                        new
                        {
                            MaHinhAnh = 37,
                            DuongDan = "/user-content/2de91d87-c82e-4db1-81e7-a7576f137422.png",
                            IsDefault = false,
                            MaSanPham = 5,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 15, 0, 30, 219, DateTimeKind.Utc).AddTicks(4082)
                        },
                        new
                        {
                            MaHinhAnh = 38,
                            DuongDan = "/user-content/75bf5150-2758-4bda-baf7-cf2897135616.png",
                            IsDefault = false,
                            MaSanPham = 5,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 15, 0, 40, 305, DateTimeKind.Utc).AddTicks(3305)
                        },
                        new
                        {
                            MaHinhAnh = 39,
                            DuongDan = "/user-content/20401a19-080b-4983-9ccd-0799a15d8474.webp",
                            IsDefault = false,
                            MaSanPham = 6,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 15, 3, 39, 697, DateTimeKind.Utc).AddTicks(2322)
                        },
                        new
                        {
                            MaHinhAnh = 40,
                            DuongDan = "/user-content/cedcdac7-562a-438f-b3fe-a1e431b293f4.webp",
                            IsDefault = false,
                            MaSanPham = 6,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 4, 4, 895, DateTimeKind.Utc).AddTicks(8437)
                        },
                        new
                        {
                            MaHinhAnh = 41,
                            DuongDan = "/user-content/b587f7d9-8de0-4d9e-8213-4de24055b44a.webp",
                            IsDefault = true,
                            MaSanPham = 6,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 4, 17, 33, DateTimeKind.Utc).AddTicks(9597)
                        },
                        new
                        {
                            MaHinhAnh = 42,
                            DuongDan = "/user-content/44fa3c5a-b5f5-4305-8b23-7383fd6fb58d.webp",
                            IsDefault = false,
                            MaSanPham = 6,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 4, 32, 599, DateTimeKind.Utc).AddTicks(3383)
                        },
                        new
                        {
                            MaHinhAnh = 43,
                            DuongDan = "/user-content/227a8e30-60b5-4525-a3f7-efdb992698a1.png",
                            IsDefault = false,
                            MaSanPham = 7,
                            Mota = "s",
                            NgayTao = new DateTime(2025, 5, 25, 15, 6, 17, 950, DateTimeKind.Utc).AddTicks(9735)
                        },
                        new
                        {
                            MaHinhAnh = 44,
                            DuongDan = "/user-content/9ec0ce09-845c-4a5a-af69-ef0d816c757b.png",
                            IsDefault = false,
                            MaSanPham = 7,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 6, 25, 59, DateTimeKind.Utc).AddTicks(381)
                        },
                        new
                        {
                            MaHinhAnh = 45,
                            DuongDan = "/user-content/28cb01e5-d934-454a-a105-1ed02dedfa36.png",
                            IsDefault = false,
                            MaSanPham = 7,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 6, 33, 76, DateTimeKind.Utc).AddTicks(7742)
                        },
                        new
                        {
                            MaHinhAnh = 46,
                            DuongDan = "/user-content/74155430-c217-4ea8-a79a-cf5557a1d245.png",
                            IsDefault = false,
                            MaSanPham = 7,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 6, 46, 588, DateTimeKind.Utc).AddTicks(7042)
                        },
                        new
                        {
                            MaHinhAnh = 47,
                            DuongDan = "/user-content/bc22666f-b6d2-4680-a449-354aebe6a431.png",
                            IsDefault = false,
                            MaSanPham = 7,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 7, 6, 31, DateTimeKind.Utc).AddTicks(9322)
                        },
                        new
                        {
                            MaHinhAnh = 48,
                            DuongDan = "/user-content/8d2f638d-2e8b-4456-9155-9ffb45b3eaf8.png",
                            IsDefault = false,
                            MaSanPham = 8,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 8, 14, 762, DateTimeKind.Utc).AddTicks(1710)
                        },
                        new
                        {
                            MaHinhAnh = 49,
                            DuongDan = "/user-content/a284f159-a24a-4bfa-a1a8-ea96db900d61.png",
                            IsDefault = false,
                            MaSanPham = 8,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 8, 31, 632, DateTimeKind.Utc).AddTicks(9623)
                        },
                        new
                        {
                            MaHinhAnh = 50,
                            DuongDan = "/user-content/88244490-1b9b-4147-a9a8-cc5dfbb9b581.png",
                            IsDefault = false,
                            MaSanPham = 8,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 8, 50, 75, DateTimeKind.Utc).AddTicks(4347)
                        },
                        new
                        {
                            MaHinhAnh = 51,
                            DuongDan = "/user-content/8e407540-b743-4ff1-95df-286736471de7.png",
                            IsDefault = false,
                            MaSanPham = 8,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 9, 0, 111, DateTimeKind.Utc).AddTicks(1204)
                        },
                        new
                        {
                            MaHinhAnh = 52,
                            DuongDan = "/user-content/3d27fb88-b296-4e2c-9c2a-eba908eafc76.webp",
                            IsDefault = false,
                            MaSanPham = 10,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 21, 27, 805, DateTimeKind.Utc).AddTicks(1149)
                        },
                        new
                        {
                            MaHinhAnh = 54,
                            DuongDan = "/user-content/a5960094-acad-4ea6-9c7c-80cb0d6e3afe.webp",
                            IsDefault = false,
                            MaSanPham = 10,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 23, 57, 107, DateTimeKind.Utc).AddTicks(7261)
                        },
                        new
                        {
                            MaHinhAnh = 56,
                            DuongDan = "/user-content/dd5a0800-f3e6-48d1-99a1-5f96bae82591.webp",
                            IsDefault = false,
                            MaSanPham = 10,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 24, 38, 790, DateTimeKind.Utc).AddTicks(5409)
                        },
                        new
                        {
                            MaHinhAnh = 57,
                            DuongDan = "/user-content/7dbf715b-f811-46df-be9c-ec466c4df33e.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 27, 20, 52, DateTimeKind.Utc).AddTicks(9913)
                        },
                        new
                        {
                            MaHinhAnh = 58,
                            DuongDan = "/user-content/5efd88f8-50db-4681-9e8e-7d31b4f85119.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 27, 28, 961, DateTimeKind.Utc).AddTicks(4938)
                        },
                        new
                        {
                            MaHinhAnh = 59,
                            DuongDan = "/user-content/8cc9c68b-86dd-48c6-a926-3bac4fed84ad.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 27, 42, 692, DateTimeKind.Utc).AddTicks(9113)
                        },
                        new
                        {
                            MaHinhAnh = 60,
                            DuongDan = "/user-content/0534e4e4-a1ef-4961-a137-bd825270cfb2.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 27, 58, 203, DateTimeKind.Utc).AddTicks(2257)
                        },
                        new
                        {
                            MaHinhAnh = 61,
                            DuongDan = "/user-content/84fc2b08-da8e-4d19-9f65-7920a3b47a04.png",
                            IsDefault = false,
                            MaSanPham = 13,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 28, 9, 213, DateTimeKind.Utc).AddTicks(8202)
                        },
                        new
                        {
                            MaHinhAnh = 62,
                            DuongDan = "/user-content/e9bd5ff4-c7c0-4c43-8a75-5f2a9eb0da16.png",
                            IsDefault = false,
                            MaSanPham = 14,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 29, 48, 114, DateTimeKind.Utc).AddTicks(9785)
                        },
                        new
                        {
                            MaHinhAnh = 63,
                            DuongDan = "/user-content/5fa677cd-e90c-4d0d-a33e-44ff34360895.png",
                            IsDefault = true,
                            MaSanPham = 14,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 29, 56, 719, DateTimeKind.Utc).AddTicks(2050)
                        },
                        new
                        {
                            MaHinhAnh = 64,
                            DuongDan = "/user-content/53f59bde-a338-431a-912a-e87fdc8b2e06.png",
                            IsDefault = false,
                            MaSanPham = 14,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 30, 8, 116, DateTimeKind.Utc).AddTicks(3458)
                        },
                        new
                        {
                            MaHinhAnh = 65,
                            DuongDan = "/user-content/6abb0d85-3e2d-4e14-806e-1a5bcb6b21d7.png",
                            IsDefault = false,
                            MaSanPham = 14,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 30, 19, 716, DateTimeKind.Utc).AddTicks(5824)
                        },
                        new
                        {
                            MaHinhAnh = 66,
                            DuongDan = "/user-content/5b931c1b-6850-4cc0-91e4-79b3ba882bbe.png",
                            IsDefault = false,
                            MaSanPham = 15,
                            Mota = "Thumbnail Images",
                            NgayTao = new DateTime(2025, 5, 25, 15, 32, 41, 18, DateTimeKind.Utc).AddTicks(7380)
                        },
                        new
                        {
                            MaHinhAnh = 67,
                            DuongDan = "/user-content/5e3de4f1-48b4-44bc-b6b5-4a1dfa03b377.png",
                            IsDefault = false,
                            MaSanPham = 15,
                            Mota = "q",
                            NgayTao = new DateTime(2025, 5, 25, 15, 32, 48, 998, DateTimeKind.Utc).AddTicks(2490)
                        },
                        new
                        {
                            MaHinhAnh = 68,
                            DuongDan = "/user-content/2689bfce-ebab-4e56-bbee-ec7ff84fbef9.png",
                            IsDefault = false,
                            MaSanPham = 15,
                            Mota = "q",
                            NgayTao = new DateTime(2025, 5, 25, 15, 33, 3, 277, DateTimeKind.Utc).AddTicks(5455)
                        },
                        new
                        {
                            MaHinhAnh = 69,
                            DuongDan = "/user-content/9185d88a-e602-40c7-85b1-5e4c4134f9d2.png",
                            IsDefault = false,
                            MaSanPham = 15,
                            Mota = "a",
                            NgayTao = new DateTime(2025, 5, 25, 15, 33, 20, 155, DateTimeKind.Utc).AddTicks(5206)
                        },
                        new
                        {
                            MaHinhAnh = 70,
                            DuongDan = "/user-content/8567fa7e-8e6f-41c5-8ca1-6c2a1fae9ce7.png",
                            IsDefault = true,
                            MaSanPham = 8,
                            Mota = "k",
                            NgayTao = new DateTime(2025, 5, 25, 21, 8, 31, 907, DateTimeKind.Utc).AddTicks(4647)
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.ProductInCategory", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ProductInCategory", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            MaSanPham = 1
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MaSanPham = 2
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MaSanPham = 3
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MaSanPham = 4
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MaSanPham = 5
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            MaSanPham = 6
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            MaSanPham = 7
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            MaSanPham = 8
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            MaSanPham = 10
                        },
                        new
                        {
                            MaDanhMuc = 1,
                            MaSanPham = 13
                        },
                        new
                        {
                            MaDanhMuc = 1,
                            MaSanPham = 14
                        },
                        new
                        {
                            MaDanhMuc = 1,
                            MaSanPham = 15
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPham", (string)null);

                    b.HasData(
                        new
                        {
                            MaSanPham = 1,
                            Gia = 150000.00m,
                            KichThuoc = "L",
                            MauSac = "Đen",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Quần chạy bộ siêu nhẹ chỉ từ 80g\n– Quần đùi nam tập thể thao Gymlab được thiết kế với công nghệ vải co giãn tốt. Cực kỳ nhẹ, tạo cảm giác mặc vô cùng thoải mái.\n– Chất vải luôn đem lại cảm giác vô cùng mềm và nhẹ. Nhờ đặc tính kết hợp tuyệt vời của vải, chiếc quần của Gymlab cực kỳ nhanh thoát mồ hôi và loại trừ hầu hết mùi cơ thể.\n– Cảm giác vải cực kỳ nhẹ và mềm, công nghệ thoát ẩm 1 chiều giúp cho chiếc quần cực kỳ nhanh khô.\n– Quần có thiết kế form 5 inch ngắn trên gối, xẻ 2 bên phù hợp tập luyện.\n– Thiết kế 2 đáy, tránh đường may dấu cộng (+) ở dưới đáy quần, đảm bảo được độ bền chắc qua tất cả các bài tập chân khó nhất.\n– Quần có màu xám in họa tiết chữ Gymlab giúp tạo điểm nhấn nổi bật.\n– Quần form ôm fit, phong cách năng động thích hợp mặc đi tập gym, chạy bộ, cardio, daily wear.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.",
                            NgayTao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = true,
                            SoLuongTon = 150,
                            TenSanPham = "Quần đùi chạy bộ nam tập thể thao "
                        },
                        new
                        {
                            MaSanPham = 2,
                            Gia = 175000.00m,
                            KichThuoc = "L",
                            MauSac = "Xám",
                            MoTa = "Thông tin cơ bản:\n\n– Người mẫu cao 1m68, nặng 65kg mặc size M vừa đẹp.\n– Chiếc áo mang đến cảm giác rộng thoải mái và cực kỳ thoáng mát khi tập.\n– Thiết kế theo dạng áo Tank sát nách, tôn dáng vai rất tốt. Tạo cảm giác vai to hơn khi mặc, giúp tăng vẻ mạnh mẽ và nam tính.\n– Cảm giác vải cực kỳ mềm mượt, công nghệ thoát ẩm 1 chiều giúp cho chiếc áo cực kỳ nhanh khô.\n– Logo được in màu bạc phản quang nhẹ vô cùng tinh tế.\n\nĐược thiết kế phù hợp với:\n\n– Tập Gym, Chạy bộ, Cardio, Daily Wear.\n– Tập luyện trong nhà và ngoài trời.\n– Phù hợp với nhiệt độ thời tiết từ 20-40 độ C.",
                            NgayTao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = true,
                            SoLuongTon = 2498,
                            TenSanPham = "ÁO TANK SÁT NÁCH NAM – ĐEN – SILVER LOGO"
                        },
                        new
                        {
                            MaSanPham = 3,
                            Gia = 150000.00m,
                            KichThuoc = "L",
                            MauSac = "Xanh Navi",
                            MoTa = "Đặc điểm nổi bật của áo công nghệ vải Activ-cool\n\n \n\nLần đầu tiên có 1 local brand đem đến Công nghệ vải đến từ Hàn Quốc với các tính năng vượt trội.\nÁo tập có tính năng: Co giãn, mềm mịn, mát mẻ, khử mùi, thoát mồ hôi cực nhanh, chống tia UV.\nĐảm bảo đem lại cảm giác mặc vô cùng thoải mái trong tất cả hoạt động hàng ngày, đặc biệt là trong hoạt động thể thao.\n \n\nThiết kế áo tập có tay co giãn của Gymlab\n\n \n\nĐội ngũ của Gymlab đã gửi rất nhiều tâm huyết vào dòng sản phẩm này, với tiêu chí thiết kế sản phẩm thoải mái khi tập luyện cũng như vượt trội về mặt thẩm mỹ.\n\n \n\nChiếc áo được may với thiết kế Raglan, tạo độ thẩm mỹ rất tốt cho người mặc, tạo cảm giác phần cầu vai và thân trên rộng hơn. Góp phần lớn vào việc tăng vẻ nam tính cho người mặc.\nChất liệu áo co giãn 4 chiều, mềm mỏng tạo cảm giác thoải mái không chỉ khi tập luyện, mà còn có thể mặc trong sinh hoạt hằng ngày. Đảm bảo khả năng khử mùi trong 48 giờ, bất chấp mọi thời tiết.\nHình in phản quang nhẹ giúp tăng tính thẩm mỹ của áo, lớp phản quang nhẹ không quá sáng, khiến cho người mặc giữ được sự lịch lãm đơn giản, không quá chói lóa.",
                            NgayTao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = false,
                            SoLuongTon = 100,
                            TenSanPham = "ÁO TẬP CÓ TAY NAM – XANH ĐEN – SILVER LOGO"
                        },
                        new
                        {
                            MaSanPham = 4,
                            Gia = 250000.00m,
                            KichThuoc = "M",
                            MauSac = "Xanh nhạt",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Áo thể thao tập gym nam Gymlab được thiết kế với công nghệ vải Activ-cool đến từ Hàn Quốc. Vải được tăng tỉ lệ Spandex giúp tăng khả năng co giãn vượt trội.\n– Chất vải luôn đem lại cảm giác vô cùng mềm và nhẹ. Nhờ đặc tính kết hợp tuyệt vời của vải, chiếc áo của Gymlab cực kỳ nhanh thoát mồ hôi và loại trừ hầu hết mùi cơ thể.\n– Áo form ôm fit, mang đến cảm giác vừa vặn và cực kỳ thoáng mát thích hợp mặc đi tập gym, thể thao.\n– Áo thiết kế tay ngắn đường may raglan (rắc lăng) tạo độ ôm tốt vào cầu vai. Giúp người mặc có cảm giác vai to và rộng hơn, tăng vẻ mạnh mẽ và nam tính của đàn ông.\n– Logo được in màu xám phản quang nhẹ vô cùng tinh tế.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.\n***Lưu ý: Màu sản phẩm có thể sẽ chênh lệch thực tế một phần nhỏ, do ảnh hưởng về độ lệch màu của ánh sáng nhưng vẫn đảm bảo chất lượng.",
                            NgayTao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = false,
                            SoLuongTon = 30,
                            TenSanPham = "Áo Tập Gym Thể Thao Cho Nam – Xám – Silver Logo"
                        },
                        new
                        {
                            MaSanPham = 5,
                            Gia = 175000.00m,
                            KichThuoc = "L",
                            MauSac = "Đen",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Áo thể thao tập gym nam Gymlab được thiết kế với công nghệ vải Activ-cool đến từ Hàn Quốc. Vải được tăng tỉ lệ Spandex giúp tăng khả năng co giãn vượt trội.\n– Chất vải luôn đem lại cảm giác vô cùng mềm và nhẹ. Nhờ đặc tính kết hợp tuyệt vời của vải, chiếc áo của Gymlab cực kỳ nhanh thoát mồ hôi và loại trừ hầu hết mùi cơ thể.\n– Áo form ôm fit, mang đến cảm giác vừa vặn và cực kỳ thoáng mát thích hợp mặc đi tập gym, thể thao.\n– Áo thiết kế tay ngắn đường may raglan (rắc lăng) tạo độ ôm tốt vào cầu vai. Giúp người mặc có cảm giác vai to và rộng hơn, tăng vẻ mạnh mẽ và nam tính của đàn ông.\n– Logo được in màu xám phản quang nhẹ vô cùng tinh tế.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.\n***Lưu ý: Màu sản phẩm có thể sẽ chênh lệch thực tế một phần nhỏ, do ảnh hưởng về độ lệch màu của ánh sáng nhưng vẫn đảm bảo chất lượng.\n\nHƯỚNG DẪN BẢO QUẢN\n– Không giặt rửa sản phẩm trực tiếp với chất tẩy rửa mạnh, sẽ gây phai màu và hư hại chất vải của sản phẩm.\n– Khi phơi nên lộn mặt trong của quần áo ra ngoài.\n– Tránh phơi đồ trực tiếp dưới nắng vì sẽ làm phai màu vải nhanh hơn.",
                            NgayTao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = false,
                            SoLuongTon = 250,
                            TenSanPham = "Áo Thể Thao Nam GYMLAB Raglan Tay Ngắn Phối Màu Tay Áo"
                        },
                        new
                        {
                            MaSanPham = 6,
                            Gia = 75000.00m,
                            KichThuoc = "L",
                            MauSac = "Đen",
                            MoTa = "ngon bổ rẻ",
                            NgayTao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NoiBat = true,
                            SoLuongTon = 34,
                            TenSanPham = "Bình Nước Tập Gym , Bình Lắc Thể Thao Có Con Lắc Lò Xo Tiện Lợi Myprotein 700ml"
                        },
                        new
                        {
                            MaSanPham = 7,
                            Gia = 750000.00m,
                            KichThuoc = "43",
                            MauSac = "Trắng",
                            MoTa = "Ngon rẻ bổ",
                            NgayTao = new DateTime(2025, 5, 12, 18, 10, 30, 817, DateTimeKind.Utc).AddTicks(801),
                            NoiBat = false,
                            SoLuongTon = 50,
                            TenSanPham = "Giày Nike Zoom Vapor Pro 2 HC ‘White’ DR6191-101"
                        },
                        new
                        {
                            MaSanPham = 8,
                            Gia = 1200000.00m,
                            KichThuoc = "42",
                            MauSac = "Đỏ",
                            MoTa = "Rẻ bổ ngon",
                            NgayTao = new DateTime(2025, 5, 12, 18, 20, 27, 620, DateTimeKind.Utc).AddTicks(550),
                            NoiBat = false,
                            SoLuongTon = 22,
                            TenSanPham = "Giày Tennis Asics Court FF Novak ‘Cranberry White’ 1041A089-605"
                        },
                        new
                        {
                            MaSanPham = 10,
                            Gia = 50000.00m,
                            KichThuoc = "30x50",
                            MauSac = "Đen",
                            MoTa = "ngon bổ re",
                            NgayTao = new DateTime(2025, 5, 13, 14, 51, 32, 15, DateTimeKind.Utc).AddTicks(8239),
                            NoiBat = false,
                            SoLuongTon = 150,
                            TenSanPham = "Khăn bông cotton"
                        },
                        new
                        {
                            MaSanPham = 13,
                            Gia = 175000.00m,
                            KichThuoc = "L",
                            MauSac = "Đen",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Trẻ trung, năng động với kiểu dáng Jogger thời thượng, quần Jogger nam lưng thun dây rút của Gymlab chắc chắn sẽ là must-have-item cho các tín đồ thời trang yêu thích phong cách đa ứng dụng.\n– Quần có thiết kế đơn giản nhưng hiện đại, kế với công nghệ vải Activ-cool đến từ Hàn Quốc. Vải được tăng tỉ lệ Spandex giúp tăng khả năng co giãn vượt trội.\n– Quần có nhiều màu sắc và kích cỡ để bạn lựa chọn, phù hợp với mọi phong cách và dáng người.\n– Thiết kế lưng thun phối dây rút cùng chi tiết bo ống, logo được in màu bạc phản quang nhẹ vô cùng tinh tế.\n– Quần jogger tập gym nam không chỉ giúp bạn thoải mái khi tập luyện, mà còn tôn lên vẻ đẹp nam tính và khỏe khoắn của bạn.\n– Quần cũng rất dễ phối đồ bạn có thể kết hợp với áo thun, áo sơ mi hay áo khoác… Để tạo nên những bộ trang phục năng động và cá tính.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.\n***Lưu ý: Màu sản phẩm có thể sẽ chênh lệch thực tế một phần nhỏ, do ảnh hưởng về độ lệch màu của ánh sáng nhưng vẫn đảm bảo chất lượng.\n\nHƯỚNG DẪN BẢO QUẢN\n– Không giặt rửa sản phẩm trực tiếp với chất tẩy rửa mạnh, sẽ gây phai màu và hư hại chất vải của sản phẩm.\n– Khi phơi nên lộn mặt trong của quần áo ra ngoài.\n– Tránh phơi đồ trực tiếp dưới nắng vì sẽ làm phai màu vải nhanh hơn.",
                            NgayTao = new DateTime(2025, 5, 23, 14, 25, 41, 920, DateTimeKind.Utc).AddTicks(6926),
                            NoiBat = false,
                            SoLuongTon = 332,
                            TenSanPham = "Quần Jogger Túi Hộp Thể Thao Unisex "
                        },
                        new
                        {
                            MaSanPham = 14,
                            Gia = 200000.00m,
                            KichThuoc = "L",
                            MauSac = "Đen",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Quần short tập gym nam 2 lớp là một sản phẩm thời trang dành cho những người yêu thích thể hình và sức khỏe.\n– Quần có thiết kế đơn giản nhưng hiện đại, với 2 lớp vải chất lượng cao, thoáng mát và co giãn tốt.\n– Quần có nhiều màu sắc và kích cỡ để bạn lựa chọn, phù hợp với mọi phong cách và dáng người.\n– Quần short tập gym nam 2 lớp không chỉ giúp bạn thoải mái khi tập luyện, mà còn tôn lên vẻ đẹp nam tính và khỏe khoắn của bạn.\n– Quần cũng rất dễ phối đồ bạn có thể kết hợp với áo thun, áo sơ mi hay áo khoác… Để tạo nên những bộ trang phục năng động và cá tính.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.\n***Lưu ý: Màu sản phẩm có thể sẽ chênh lệch thực tế một phần nhỏ, do ảnh hưởng về độ lệch màu của ánh sáng nhưng vẫn đảm bảo chất lượng.\n\nHƯỚNG DẪN BẢO QUẢN\n– Không giặt rửa sản phẩm trực tiếp với chất tẩy rửa mạnh, sẽ gây phai màu và hư hại chất vải của sản phẩm.\n– Khi phơi nên lộn mặt trong của quần áo ra ngoài.\n– Tránh phơi đồ trực tiếp dưới nắng vì sẽ làm phai màu vải nhanh hơn.",
                            NgayTao = new DateTime(2025, 5, 25, 13, 53, 33, 552, DateTimeKind.Utc).AddTicks(7552),
                            NoiBat = false,
                            SoLuongTon = 123,
                            TenSanPham = "Quần short tập gym nam 2 lớp "
                        },
                        new
                        {
                            MaSanPham = 15,
                            Gia = 250000.00m,
                            KichThuoc = "m",
                            MauSac = "Đen",
                            MoTa = "ĐẶC ĐIỂM NỔI BẬT\n– Quần short tập gym nam 2 lớp là một sản phẩm thời trang dành cho những người yêu thích thể hình và sức khỏe.\n– Quần có thiết kế đơn giản nhưng hiện đại, với 2 lớp vải chất lượng cao, thoáng mát và co giãn tốt.\n– Quần có nhiều màu sắc và kích cỡ để bạn lựa chọn, phù hợp với mọi phong cách và dáng người.\n– Quần short tập gym nam 2 lớp không chỉ giúp bạn thoải mái khi tập luyện, mà còn tôn lên vẻ đẹp nam tính và khỏe khoắn của bạn.\n– Quần cũng rất dễ phối đồ bạn có thể kết hợp với áo thun, áo sơ mi hay áo khoác… Để tạo nên những bộ trang phục năng động và cá tính.\n– Sản phẩm được đảm bảo với quy trình sản xuất chất lượng với đường may chắc chắn, tỉ mỉ từng chi tiết.\n***Lưu ý: Màu sản phẩm có thể sẽ chênh lệch thực tế một phần nhỏ, do ảnh hưởng về độ lệch màu của ánh sáng nhưng vẫn đảm bảo chất lượng.\n\nHƯỚNG DẪN BẢO QUẢN\n– Không giặt rửa sản phẩm trực tiếp với chất tẩy rửa mạnh, sẽ gây phai màu và hư hại chất vải của sản phẩm.\n– Khi phơi nên lộn mặt trong của quần áo ra ngoài.\n– Tránh phơi đồ trực tiếp dưới nắng vì sẽ làm phai màu vải nhanh hơn.",
                            NgayTao = new DateTime(2025, 5, 25, 15, 32, 41, 18, DateTimeKind.Utc).AddTicks(6589),
                            NoiBat = false,
                            SoLuongTon = 31,
                            TenSanPham = "Quần short tập gym nam 2 lớp"
                        });
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopGYM.Data.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DanhGia", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.AppUser", "AppUser")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopGYM.Data.Entities.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DonHang", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.AppUser", "AppUser")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.GioHang", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.AppUser", "AppUser")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopGYM.Data.Entities.SanPham", "SanPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.HinhAnh", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.DanhGia", "DanhGia")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaDanhGia")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ShopGYM.Data.Entities.SanPham", "SanPham")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.ProductInCategory", b =>
                {
                    b.HasOne("ShopGYM.Data.Entities.DanhMuc", "DanhMuc")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopGYM.Data.Entities.SanPham", "SanPham")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.AppUser", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DanhGia", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DanhMuc", b =>
                {
                    b.Navigation("ProductInCategories");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("ShopGYM.Data.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhAnhs");

                    b.Navigation("ProductInCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
